### ISSUE TITLE
Add support for "Perspectives"

### ISSUE THREAD

**Issue by sbennett33** [balexand/sanity#77]
Sanity now supports "perspectives" which allow you to specify whether or not you want to see draft documents or not.

https://www.sanity.io/blog/introducing-perspectives-sanity-previews

> There are three perspectives available as part of this release, available now for all Sanity customers on any project plan:
> 
> previewDrafts: retrieves documents in their draft version (or published if no drafts exist). It will also add an originalId property to documents for additional control. As explored below, we designed previewDrafts to simplify the developer experience for building content previews.
> published: retrieves only the published version of documents. You can use this perspective as an extra layer of assurance to avoid draft content leaks for authenticated requests in production.
> raw: preserves the same functionality of queries as they worked pre-Perspectives (and is the default perspective if one is not specified). This means that Perspectives is a non-breaking feature.

**Comment by sbennett33** [comment]
PR incoming soon

**Comment by balexand** [comment]
We should support perspectives in the following functions:

- [ ] `query` (See #78)
- [ ] `stream`

**Comment by sbennett33** [comment]
As you pointed out, we can already pass the perspective as a query param. I'm not sure what would be involved in adding that support for streams.

**Comment by balexand** [comment]
I've updated the docs for [`Sanity.query/3`](https://hexdocs.pm/sanity/Sanity.html#query/3) to describe how to use perspectives. I've also updated [`Sanity.stream/1`](https://hexdocs.pm/sanity/Sanity.html#stream/1) to support perspectives.

Thanks!
